### chat completions - non-stream
# gpt-4o
# claude-3-5-sonnet-20240620
POST {{host}}/api/chat/completions
Content-Type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ]
}

### chat completions - stream
POST {{host}}/api/chat/completions
Content-Type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": true
}

### chat completions By chatClient - non-stream
POST {{host}}/api/chat/completions/chat-client
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ]
}

### chat completions By chatClient - stream
POST {{host}}/api/chat/completions/chat-client
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": true
}

### chat completions By webClient - non-stream
POST {{host}}/api/chat/completions/webclient
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ]
}

### chat completions By webClient - stream
POST {{host}}/api/chat/completions/webclient
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": true
}
