### health check
GET {{host}}/health

### echo
POST {{host}}/echo
Content-Type: application/json

{
  "message": "Hello, World!"
}

### openAi - chat completions - non-stream
POST {{aiProvider.openAi.baseUrl}}/v1/chat/completions
Authorization: Bearer {{aiProvider.openAi.apiKey}}
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ]
}

### openAi - chat completions - stream
POST {{aiProvider.openAi.baseUrl}}/v1/chat/completions
Authorization: Bearer {{aiProvider.openAi.apiKey}}
Content-Type: application/json

{
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": true
}

### anthropic - message - non-stream
POST {{aiProvider.anthropic.baseUrl}}/v1/messages
x-api-key: {{aiProvider.anthropic.apiKey}}
anthropic-version: 2023-06-01
Content-Type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "max_tokens": 1024,
  "messages": [
    {
      "role": "user",
      "content": "Hello, world"
    }
  ]
}

### anthropic - message - stream
POST {{aiProvider.anthropic.baseUrl}}/v1/messages
x-api-key: {{aiProvider.anthropic.apiKey}}
anthropic-version: 2023-06-01
Content-Type: application/json

{
  "model": "claude-3-5-sonnet-20240620",
  "max_tokens": 1024,
  "messages": [
    {
      "role": "user",
      "content": "Hello, world"
    }
  ],
  "stream": true
}
